// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sklep.Models;

#nullable disable

namespace sklep.Migrations
{
    [DbContext(typeof(SklepContext))]
    [Migration("20241202075659_DatabaseInit")]
    partial class DatabaseInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("sklep.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("sklep.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("sklep.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rośliny doniczkowe"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rośliny ogrodowe"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sukulenty"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Zioła"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kwiaty cięte"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Drzewka bonsai"
                        });
                });

            modelBuilder.Entity("sklep.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("sklep.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("sklep.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Piękna roślina: Monstera deliciosa. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Monstera deliciosa",
                            Price = 15m,
                            StockQuantity = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Piękna roślina: Fikus benjamina. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/monstera.jpg",
                            Name = "Fikus benjamina",
                            Price = 20m,
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Piękna roślina: Sansewieria. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/sansevieria.jpg",
                            Name = "Sansewieria",
                            Price = 25m,
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Piękna roślina: Dracena marginata. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Dracena marginata",
                            Price = 30m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "Piękna roślina: Zamiokulkas zamiolistny. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/monstera.jpg",
                            Name = "Zamiokulkas zamiolistny",
                            Price = 35m,
                            StockQuantity = 13
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Description = "Piękna roślina: Aloes zwyczajny. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/sansevieria.jpg",
                            Name = "Aloes zwyczajny",
                            Price = 40m,
                            StockQuantity = 16
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Piękna roślina: Kaktus opuncja. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Kaktus opuncja",
                            Price = 45m,
                            StockQuantity = 19
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Piękna roślina: Kalanchoe. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/monstera.jpg",
                            Name = "Kalanchoe",
                            Price = 50m,
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Piękna roślina: Bonsai fikus ginseng. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/sansevieria.jpg",
                            Name = "Bonsai fikus ginseng",
                            Price = 55m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Piękna roślina: Rozmaryn. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Rozmaryn",
                            Price = 60m,
                            StockQuantity = 28
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            Description = "Piękna roślina: Bazylia. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/monstera.jpg",
                            Name = "Bazylia",
                            Price = 65m,
                            StockQuantity = 31
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            Description = "Piękna roślina: Lawenda. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/sansevieria.jpg",
                            Name = "Lawenda",
                            Price = 70m,
                            StockQuantity = 34
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Description = "Piękna roślina: Mięta pieprzowa. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Mięta pieprzowa",
                            Price = 75m,
                            StockQuantity = 37
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Piękna roślina: Chryzantema. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/monstera.jpg",
                            Name = "Chryzantema",
                            Price = 80m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "Piękna roślina: Róża. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/sansevieria.jpg",
                            Name = "Róża",
                            Price = 85m,
                            StockQuantity = 43
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Description = "Piękna roślina: Tulipan. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Tulipan",
                            Price = 90m,
                            StockQuantity = 46
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            Description = "Piękna roślina: Stokrotka. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/monstera.jpg",
                            Name = "Stokrotka",
                            Price = 95m,
                            StockQuantity = 49
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 6,
                            Description = "Piękna roślina: Bluszcz pospolity. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/sansevieria.jpg",
                            Name = "Bluszcz pospolity",
                            Price = 100m,
                            StockQuantity = 2
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Description = "Piękna roślina: Paprotka. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Paprotka",
                            Price = 105m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Description = "Piękna roślina: Anturium. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/monstera.jpg",
                            Name = "Anturium",
                            Price = 110m,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Description = "Piękna roślina: Orchidea. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/sansevieria.jpg",
                            Name = "Orchidea",
                            Price = 115m,
                            StockQuantity = 11
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Description = "Piękna roślina: Palma areka. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Palma areka",
                            Price = 120m,
                            StockQuantity = 14
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            Description = "Piękna roślina: Juka. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/monstera.jpg",
                            Name = "Juka",
                            Price = 125m,
                            StockQuantity = 17
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 6,
                            Description = "Piękna roślina: Liwia. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/sansevieria.jpg",
                            Name = "Liwia",
                            Price = 130m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            Description = "Piękna roślina: Kroton. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Kroton",
                            Price = 135m,
                            StockQuantity = 23
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            Description = "Piękna roślina: Skrzydłokwiat. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/monstera.jpg",
                            Name = "Skrzydłokwiat",
                            Price = 140m,
                            StockQuantity = 26
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Description = "Piękna roślina: Grubosz drzewiasty. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/sansevieria.jpg",
                            Name = "Grubosz drzewiasty",
                            Price = 145m,
                            StockQuantity = 29
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 4,
                            Description = "Piękna roślina: Eszeweria. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Eszeweria",
                            Price = 150m,
                            StockQuantity = 32
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 5,
                            Description = "Piękna roślina: Haworcja. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/monstera.jpg",
                            Name = "Haworcja",
                            Price = 155m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 6,
                            Description = "Piękna roślina: Szałwia lekarska. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/sansevieria.jpg",
                            Name = "Szałwia lekarska",
                            Price = 160m,
                            StockQuantity = 38
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 1,
                            Description = "Piękna roślina: Tymianek. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Tymianek",
                            Price = 165m,
                            StockQuantity = 41
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            Description = "Piękna roślina: Oregano. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/monstera.jpg",
                            Name = "Oregano",
                            Price = 170m,
                            StockQuantity = 44
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 3,
                            Description = "Piękna roślina: Begonia. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/sansevieria.jpg",
                            Name = "Begonia",
                            Price = 175m,
                            StockQuantity = 47
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            Description = "Piękna roślina: Geranium. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Geranium",
                            Price = 180m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 5,
                            Description = "Piękna roślina: Storczyk falenopsis. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/monstera.jpg",
                            Name = "Storczyk falenopsis",
                            Price = 185m,
                            StockQuantity = 3
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 6,
                            Description = "Piękna roślina: Kaktus gwiazda betlejemska. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/sansevieria.jpg",
                            Name = "Kaktus gwiazda betlejemska",
                            Price = 190m,
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 1,
                            Description = "Piękna roślina: Hibiskus. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Hibiskus",
                            Price = 195m,
                            StockQuantity = 9
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 2,
                            Description = "Piękna roślina: Azalia. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/monstera.jpg",
                            Name = "Azalia",
                            Price = 15m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 3,
                            Description = "Piękna roślina: Magnolia. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/sansevieria.jpg",
                            Name = "Magnolia",
                            Price = 20m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            Description = "Piękna roślina: Drzewko cytrynowe. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Drzewko cytrynowe",
                            Price = 25m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 5,
                            Description = "Piękna roślina: Drzewko oliwne. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/monstera.jpg",
                            Name = "Drzewko oliwne",
                            Price = 30m,
                            StockQuantity = 21
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 6,
                            Description = "Piękna roślina: Fiołek afrykański. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/sansevieria.jpg",
                            Name = "Fiołek afrykański",
                            Price = 35m,
                            StockQuantity = 24
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 1,
                            Description = "Piękna roślina: Pelargonia. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Pelargonia",
                            Price = 40m,
                            StockQuantity = 27
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 2,
                            Description = "Piękna roślina: Amarylis. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/monstera.jpg",
                            Name = "Amarylis",
                            Price = 45m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 3,
                            Description = "Piękna roślina: Asparagus. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/sansevieria.jpg",
                            Name = "Asparagus",
                            Price = 50m,
                            StockQuantity = 33
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 4,
                            Description = "Piękna roślina: Szeflera. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Szeflera",
                            Price = 55m,
                            StockQuantity = 36
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 5,
                            Description = "Piękna roślina: Papryczka chili. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/monstera.jpg",
                            Name = "Papryczka chili",
                            Price = 60m,
                            StockQuantity = 39
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 6,
                            Description = "Piękna roślina: Rozplenica japońska. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/sansevieria.jpg",
                            Name = "Rozplenica japońska",
                            Price = 65m,
                            StockQuantity = 42
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 1,
                            Description = "Piękna roślina: Kocanka włochata. Idealna do domu lub ogrodu.",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Kocanka włochata",
                            Price = 70m,
                            StockQuantity = 45
                        });
                });

            modelBuilder.Entity("sklep.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("sklep.Models.Cart", b =>
                {
                    b.HasOne("sklep.Models.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("sklep.Models.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("sklep.Models.CartItem", b =>
                {
                    b.HasOne("sklep.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sklep.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("sklep.Models.Order", b =>
                {
                    b.HasOne("sklep.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("sklep.Models.OrderItem", b =>
                {
                    b.HasOne("sklep.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sklep.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("sklep.Models.Product", b =>
                {
                    b.HasOne("sklep.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("sklep.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("sklep.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("sklep.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("sklep.Models.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
