// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sklep.Models;

#nullable disable

namespace sklep.Migrations
{
    [DbContext(typeof(SklepContext))]
    [Migration("20241201003728_Cart")]
    partial class Cart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("sklep.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("sklep.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("sklep.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Indoor Plants"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Outdoor Plants"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Succulents"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Herbs"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Trees"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Flowers"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Air Purifying Plants"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Tropical Plants"
                        });
                });

            modelBuilder.Entity("sklep.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "Description for product 1",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 1",
                            Price = 11m,
                            StockQuantity = 2
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            Description = "Description for product 2",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 2",
                            Price = 12m,
                            StockQuantity = 3
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            Description = "Description for product 3",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 3",
                            Price = 13m,
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            Description = "Description for product 4",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 4",
                            Price = 14m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 6,
                            Description = "Description for product 5",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 5",
                            Price = 15m,
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 7,
                            Description = "Description for product 6",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 6",
                            Price = 16m,
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 8,
                            Description = "Description for product 7",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 7",
                            Price = 17m,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 9,
                            Description = "Description for product 8",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 8",
                            Price = 18m,
                            StockQuantity = 9
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 10,
                            Description = "Description for product 9",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 9",
                            Price = 19m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Description for product 10",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 10",
                            Price = 20m,
                            StockQuantity = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Description for product 11",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 11",
                            Price = 21m,
                            StockQuantity = 2
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Description for product 12",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 12",
                            Price = 22m,
                            StockQuantity = 3
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Description = "Description for product 13",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 13",
                            Price = 23m,
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "Description for product 14",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 14",
                            Price = 24m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 6,
                            Description = "Description for product 15",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 15",
                            Price = 25m,
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 7,
                            Description = "Description for product 16",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 16",
                            Price = 26m,
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 8,
                            Description = "Description for product 17",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 17",
                            Price = 27m,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 9,
                            Description = "Description for product 18",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 18",
                            Price = 28m,
                            StockQuantity = 9
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 10,
                            Description = "Description for product 19",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 19",
                            Price = 29m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Description = "Description for product 20",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 20",
                            Price = 10m,
                            StockQuantity = 1
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Description = "Description for product 21",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 21",
                            Price = 11m,
                            StockQuantity = 2
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Description = "Description for product 22",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 22",
                            Price = 12m,
                            StockQuantity = 3
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            Description = "Description for product 23",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 23",
                            Price = 13m,
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            Description = "Description for product 24",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 24",
                            Price = 14m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 6,
                            Description = "Description for product 25",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 25",
                            Price = 15m,
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 7,
                            Description = "Description for product 26",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 26",
                            Price = 16m,
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 8,
                            Description = "Description for product 27",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 27",
                            Price = 17m,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 9,
                            Description = "Description for product 28",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 28",
                            Price = 18m,
                            StockQuantity = 9
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 10,
                            Description = "Description for product 29",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 29",
                            Price = 19m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 1,
                            Description = "Description for product 30",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 30",
                            Price = 20m,
                            StockQuantity = 1
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            Description = "Description for product 31",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 31",
                            Price = 21m,
                            StockQuantity = 2
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            Description = "Description for product 32",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 32",
                            Price = 22m,
                            StockQuantity = 3
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            Description = "Description for product 33",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 33",
                            Price = 23m,
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 5,
                            Description = "Description for product 34",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 34",
                            Price = 24m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 6,
                            Description = "Description for product 35",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 35",
                            Price = 25m,
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 7,
                            Description = "Description for product 36",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 36",
                            Price = 26m,
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 8,
                            Description = "Description for product 37",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 37",
                            Price = 27m,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 9,
                            Description = "Description for product 38",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 38",
                            Price = 28m,
                            StockQuantity = 9
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 10,
                            Description = "Description for product 39",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 39",
                            Price = 29m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 1,
                            Description = "Description for product 40",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 40",
                            Price = 10m,
                            StockQuantity = 1
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 2,
                            Description = "Description for product 41",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 41",
                            Price = 11m,
                            StockQuantity = 2
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 3,
                            Description = "Description for product 42",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 42",
                            Price = 12m,
                            StockQuantity = 3
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 4,
                            Description = "Description for product 43",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 43",
                            Price = 13m,
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            Description = "Description for product 44",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 44",
                            Price = 14m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 6,
                            Description = "Description for product 45",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 45",
                            Price = 15m,
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 7,
                            Description = "Description for product 46",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 46",
                            Price = 16m,
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 8,
                            Description = "Description for product 47",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 47",
                            Price = 17m,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 9,
                            Description = "Description for product 48",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 48",
                            Price = 18m,
                            StockQuantity = 9
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 10,
                            Description = "Description for product 49",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 49",
                            Price = 19m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 1,
                            Description = "Description for product 50",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 50",
                            Price = 20m,
                            StockQuantity = 1
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 2,
                            Description = "Description for product 51",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 51",
                            Price = 21m,
                            StockQuantity = 2
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 3,
                            Description = "Description for product 52",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 52",
                            Price = 22m,
                            StockQuantity = 3
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 4,
                            Description = "Description for product 53",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 53",
                            Price = 23m,
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 5,
                            Description = "Description for product 54",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 54",
                            Price = 24m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 6,
                            Description = "Description for product 55",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 55",
                            Price = 25m,
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 7,
                            Description = "Description for product 56",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 56",
                            Price = 26m,
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 8,
                            Description = "Description for product 57",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 57",
                            Price = 27m,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 9,
                            Description = "Description for product 58",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 58",
                            Price = 28m,
                            StockQuantity = 9
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 10,
                            Description = "Description for product 59",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 59",
                            Price = 29m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 1,
                            Description = "Description for product 60",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 60",
                            Price = 10m,
                            StockQuantity = 1
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 2,
                            Description = "Description for product 61",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 61",
                            Price = 11m,
                            StockQuantity = 2
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 3,
                            Description = "Description for product 62",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 62",
                            Price = 12m,
                            StockQuantity = 3
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 4,
                            Description = "Description for product 63",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 63",
                            Price = 13m,
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 5,
                            Description = "Description for product 64",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 64",
                            Price = 14m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 6,
                            Description = "Description for product 65",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 65",
                            Price = 15m,
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 7,
                            Description = "Description for product 66",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 66",
                            Price = 16m,
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 8,
                            Description = "Description for product 67",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 67",
                            Price = 17m,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 9,
                            Description = "Description for product 68",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 68",
                            Price = 18m,
                            StockQuantity = 9
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 10,
                            Description = "Description for product 69",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 69",
                            Price = 19m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 1,
                            Description = "Description for product 70",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 70",
                            Price = 20m,
                            StockQuantity = 1
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 2,
                            Description = "Description for product 71",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 71",
                            Price = 21m,
                            StockQuantity = 2
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 3,
                            Description = "Description for product 72",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 72",
                            Price = 22m,
                            StockQuantity = 3
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 4,
                            Description = "Description for product 73",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 73",
                            Price = 23m,
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 5,
                            Description = "Description for product 74",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 74",
                            Price = 24m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 6,
                            Description = "Description for product 75",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 75",
                            Price = 25m,
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 7,
                            Description = "Description for product 76",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 76",
                            Price = 26m,
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 8,
                            Description = "Description for product 77",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 77",
                            Price = 27m,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 9,
                            Description = "Description for product 78",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 78",
                            Price = 28m,
                            StockQuantity = 9
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 10,
                            Description = "Description for product 79",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 79",
                            Price = 29m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 1,
                            Description = "Description for product 80",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 80",
                            Price = 10m,
                            StockQuantity = 1
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 2,
                            Description = "Description for product 81",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 81",
                            Price = 11m,
                            StockQuantity = 2
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 3,
                            Description = "Description for product 82",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 82",
                            Price = 12m,
                            StockQuantity = 3
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 4,
                            Description = "Description for product 83",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 83",
                            Price = 13m,
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 5,
                            Description = "Description for product 84",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 84",
                            Price = 14m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 6,
                            Description = "Description for product 85",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 85",
                            Price = 15m,
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 7,
                            Description = "Description for product 86",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 86",
                            Price = 16m,
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 8,
                            Description = "Description for product 87",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 87",
                            Price = 17m,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 9,
                            Description = "Description for product 88",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 88",
                            Price = 18m,
                            StockQuantity = 9
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 10,
                            Description = "Description for product 89",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 89",
                            Price = 19m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 1,
                            Description = "Description for product 90",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 90",
                            Price = 20m,
                            StockQuantity = 1
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 2,
                            Description = "Description for product 91",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 91",
                            Price = 21m,
                            StockQuantity = 2
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 3,
                            Description = "Description for product 92",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 92",
                            Price = 22m,
                            StockQuantity = 3
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 4,
                            Description = "Description for product 93",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 93",
                            Price = 23m,
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 5,
                            Description = "Description for product 94",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 94",
                            Price = 24m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 6,
                            Description = "Description for product 95",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 95",
                            Price = 25m,
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 7,
                            Description = "Description for product 96",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 96",
                            Price = 26m,
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 8,
                            Description = "Description for product 97",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 97",
                            Price = 27m,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 9,
                            Description = "Description for product 98",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 98",
                            Price = 28m,
                            StockQuantity = 9
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 10,
                            Description = "Description for product 99",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 99",
                            Price = 29m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 1,
                            Description = "Description for product 100",
                            ImageUrl = "http://localhost:5000/productimg/fikus.jpg",
                            Name = "Product 100",
                            Price = 10m,
                            StockQuantity = 1
                        });
                });

            modelBuilder.Entity("sklep.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john@example.com",
                            PasswordHash = "hashedpassword1",
                            Username = "john_doe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane@example.com",
                            PasswordHash = "hashedpassword2",
                            Username = "jane_doe"
                        },
                        new
                        {
                            Id = 3,
                            Email = "alex@example.com",
                            PasswordHash = "hashedpassword3",
                            Username = "alex_smith"
                        });
                });

            modelBuilder.Entity("sklep.Models.Cart", b =>
                {
                    b.HasOne("sklep.Models.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("sklep.Models.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("sklep.Models.CartItem", b =>
                {
                    b.HasOne("sklep.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sklep.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("sklep.Models.Product", b =>
                {
                    b.HasOne("sklep.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("sklep.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("sklep.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("sklep.Models.User", b =>
                {
                    b.Navigation("Cart");
                });
#pragma warning restore 612, 618
        }
    }
}
